{{- range $domain := .Values.domains }}
{{- if $domain.basic_auth }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $domain.host }}-basic-auth-secret
  namespace: app-{{ $.Values.location }}
data:
  users: |2
    {{ $domain.basic_auth | b64enc }}
{{- end }}
{{- end }}
