{{- range $domain := .Values.domains }}
{{- if and $domain.host $domain.tls }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $domain.host }}
  namespace: app-home
spec:
  secretName: {{ $domain.host }}
  commonName: {{ $domain.host }}
  dnsNames:
  - {{ $domain.host }}
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
{{- end }}
{{- end }}
