apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: app-{{ .Values.location }}
  labels:
    xingrz/app: {{ .Values.name }}
    xingrz/location: {{ .Values.location }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      xingrz/app: {{ .Values.name }}
      xingrz/location: {{ .Values.location }}
  template:
    metadata:
      name: {{ .Values.name }}
      labels:
        xingrz/app: {{ .Values.name }}
        xingrz/location: {{ .Values.location }}
    spec:
      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.image }}
        {{- if .Values.container }}
        {{- toYaml .Values.container | nindent 8 }}
        {{- end }}
        {{- if .Values.mounts }}
        volumeMounts:
          {{- range $name, $mount := .Values.mounts }}
          {{- if $mount.mount }}
        - name: {{ $name }}
          mountPath: {{ $mount.mount }}
          {{- end }}
          {{- end }}
        {{- end }}
      {{- if .Values.mounts }}
      volumes:
        {{- range $name, $mount := .Values.mounts }}
      - name: {{ $name }}
        persistentVolumeClaim:
          claimName: {{ $.Values.name }}-pvc-{{ $name }}
        {{- end }}
      {{- end }}
      {{- if .Values.deployment }}
      {{- toYaml .Values.deployment | nindent 6 }}
      {{- end }}
      imagePullSecrets:
      - name: aliyun-container-registry
      nodeSelector:
        xingrz/location: {{ .Values.location }}
