{{- range $i, $publish := .Values.publish }}
{{- if eq $publish.target "cluster" }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Values.name }}
  namespace: app-{{ $.Values.location }}
  labels:
    xingrz/app: {{ $.Values.name }}
    xingrz/location: {{ $.Values.location }}
spec:
  type: ClusterIP
  ports:
    {{- toYaml $publish.ports | nindent 4 }}
  selector:
    xingrz/app: {{ $.Values.name }}
    xingrz/location: {{ $.Values.location }}
{{- end }}
{{- end }}
